targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_schema/graphql_api.dart
              schema: schema.graphql
              queries_glob: lib/graphql_schema/**.graphql